apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: shoppinglist
spec:
  ports:
    - port: 15672
  selector:
    app: shoppinglist
    tier: rabbitmq
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: shoppinglist-rabbitmq
  labels:
    app: shoppinglist
spec:
  ports:
    - port: 5672
  selector:
    app: shoppinglist
    tier: rabbitmq
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: shoppinglist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppinglist
      tier: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shoppinglist
        tier: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
