apiVersion: v1
kind: Service
metadata:
  name: shoppinglist-pgadmin
  labels:
    app: shoppinglist
spec:
  ports:
    - port: 5050
      targetPort: 80
  selector:
    app: shoppinglist
    tier: pgadmin
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pv-claim
  labels:
    app: shoppinglist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: shoppinglist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppinglist
      tier: pgadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shoppinglist
        tier: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@example.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: Qwerty_1
        - name: PGADMIN_LISTEN_PORT
          value: "80"
        ports:
        - containerPort: 80
        resources:
        volumeMounts:
        - name: pgadmin-persistent-storage
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-persistent-storage
        persistentVolumeClaim:
          claimName: pgadmin-pv-claim
